In [11]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

In [14]:
iris=pd.read_csv(r"F:\Data_Science\Week_13\09-06-2019_PCA & PROJECT 5 TEXT ANALYSIS MODELS\AG\iris.csv")

In [15]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [16]:
iris=iris.drop(["Species"],axis=1)

In [17]:
iris.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [18]:
# Create the Scaler object
scaler = preprocessing.StandardScaler()

In [19]:
# Fit your data on the scaler object
x_std = scaler.fit_transform(iris)

In [23]:
x_std.shape

(150, 4)

In [24]:
x_std.min()

-2.433947141908088

In [25]:
x_std.max()

3.090775248299425

In [26]:
n=x_std.shape[0]

Calculating covariance

In [27]:
n

150

In [28]:
x_bar=np.mean(x_std)

In [29]:
x_bar

-4.855375361027351e-16

Method # 1

In [47]:
cov=(((x_std-x_bar).T)).dot(x_std-x_bar)/(n-1)

In [48]:
cov

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

Method #2

In [49]:
cov1=(((x_std.T-x_bar.T))).dot(x_std-x_bar)/(n-1)

In [50]:
cov1

array([[ 1.00671141, -0.11835884,  0.87760447,  0.82343066],
       [-0.11835884,  1.00671141, -0.43131554, -0.36858315],
       [ 0.87760447, -0.43131554,  1.00671141,  0.96932762],
       [ 0.82343066, -0.36858315,  0.96932762,  1.00671141]])

Computing eigen values and eigen vectors

In [54]:
lamda,w=np.linalg.eig(cov)

In [56]:
lamda

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

In [57]:
w

array([[ 0.52106591, -0.37741762, -0.71956635,  0.26128628],
       [-0.26934744, -0.92329566,  0.24438178, -0.12350962],
       [ 0.5804131 , -0.02449161,  0.14212637, -0.80144925],
       [ 0.56485654, -0.06694199,  0.63427274,  0.52359713]])

Reducing the dimensions

In [59]:
w_trim=w[:,:2]

In [61]:
w_trim.shape

(4, 2)

Transposed space(T)

In [62]:
T=x_std.dot(w_trim)

In [63]:
T.shape

(150, 2)

Using pre-defined function

In [68]:
from sklearn.decomposition import PCA

In [73]:
pca_data=PCA().fit(x_std)

In [74]:
(pca_data.explained_variance_ratio_)*100

array([72.96244541, 22.85076179,  3.66892189,  0.51787091])

In [76]:
pca_data.components_

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [ 0.37741762,  0.92329566,  0.02449161,  0.06694199],
       [-0.71956635,  0.24438178,  0.14212637,  0.63427274],
       [-0.26128628,  0.12350962,  0.80144925, -0.52359713]])

In [79]:
pca_data.explained_variance_

array([2.93808505, 0.9201649 , 0.14774182, 0.02085386])

SVD

In [80]:
np.linalg.svd(x_std)

(array([[-1.08239531e-01, -4.09957970e-02,  2.72186462e-02, ...,
          5.43380310e-02,  1.96438400e-03,  2.46978090e-03],
        [-9.94577561e-02,  5.75731483e-02,  5.00034005e-02, ...,
          5.12936114e-03,  8.48544595e-02,  5.83496936e-03],
        [-1.12996303e-01,  2.92000319e-02, -9.42089147e-03, ...,
          2.75184277e-02,  1.78604309e-01,  1.49419118e-01],
        ...,
        [ 7.27030413e-02, -2.29793601e-02, -3.84023516e-02, ...,
          9.89532683e-01, -1.25488246e-02, -7.17729676e-04],
        [ 6.56112167e-02, -8.63643414e-02, -1.98939364e-01, ...,
         -1.41206665e-02,  9.52049996e-01, -2.32048811e-02],
        [ 4.59137323e-02,  2.07800179e-03, -1.12588405e-01, ...,
         -8.30595907e-04, -2.19201906e-02,  9.77300244e-01]]),
 array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239]),
 array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
        [-0.37741762, -0.92329566, -0.02449161, -0.06694199],
        [ 0.71956635, -0.24438178, -0.14212

In [81]:
u,sigma,v=np.linalg.svd(x_std)

In [82]:
u

array([[-1.08239531e-01, -4.09957970e-02,  2.72186462e-02, ...,
         5.43380310e-02,  1.96438400e-03,  2.46978090e-03],
       [-9.94577561e-02,  5.75731483e-02,  5.00034005e-02, ...,
         5.12936114e-03,  8.48544595e-02,  5.83496936e-03],
       [-1.12996303e-01,  2.92000319e-02, -9.42089147e-03, ...,
         2.75184277e-02,  1.78604309e-01,  1.49419118e-01],
       ...,
       [ 7.27030413e-02, -2.29793601e-02, -3.84023516e-02, ...,
         9.89532683e-01, -1.25488246e-02, -7.17729676e-04],
       [ 6.56112167e-02, -8.63643414e-02, -1.98939364e-01, ...,
        -1.41206665e-02,  9.52049996e-01, -2.32048811e-02],
       [ 4.59137323e-02,  2.07800179e-03, -1.12588405e-01, ...,
        -8.30595907e-04, -2.19201906e-02,  9.77300244e-01]])

In [83]:
sigma

array([20.92306556, 11.7091661 ,  4.69185798,  1.76273239])

In [84]:
##V is nothing but w
v

array([[ 0.52106591, -0.26934744,  0.5804131 ,  0.56485654],
       [-0.37741762, -0.92329566, -0.02449161, -0.06694199],
       [ 0.71956635, -0.24438178, -0.14212637, -0.63427274],
       [ 0.26128628, -0.12350962, -0.80144925,  0.52359713]])

In [85]:
u.shape

(150, 150)

In [86]:
sigma.shape

(4,)

In [87]:
v.shape

(4, 4)